"""
C++ implementation of a modelling software for Markov jump processes. Contains a text-based model builder, utilities for stochastic simulation, a krylov-based solver of the master equation, tools for filtering and parameter inference
"""
from __future__ import annotations
import numpy
import scipy.sparse
import typing
__all__ = ['Event', 'Krylov', 'KrylovBackwardFilter', 'KrylovFilter', 'KrylovFilterMem', 'KrylovPropagator', 'KrylovSolver', 'LogNormalNoise', 'MEInference', 'MJP', 'MasterEquation', 'NoiseModel', 'NormalNoise', 'ObservationModel', 'Param', 'PosteriorSimulator', 'Rate', 'Simulator', 'Species', 'Transform', 'batched_filter', 'batched_filter_list', 'simulate', 'simulate_batched', 'simulate_full', 'simulate_posterior', 'simulate_posterior_batched']
class Event:
    name: str
    @typing.overload
    def __init__(self, event: Event) -> None:
        ...
    @typing.overload
    def __init__(self, name: str, input_species: list[str], output_species: list[str], rate: Rate, propensity_callable: tuple, change_vec: list[int], species_dict: dict = {}) -> None:
        ...
    def hazard(self, state: numpy.ndarray[numpy.float64]) -> float:
        ...
    def propensity(self, state: numpy.ndarray[numpy.float64]) -> float:
        ...
    @property
    def change_vec(self) -> list[int]:
        ...
    @property
    def input_species(self) -> list[str]:
        ...
    @property
    def output_species(self) -> list[str]:
        ...
    @property
    def rate(self) -> Rate:
        ...
    @property
    def species_dict(self) -> dict:
        ...
class Krylov:
    def __init__(self, generator: scipy.sparse.csr_matrix, initial: numpy.ndarray[numpy.float64[m, 1]], order: int) -> None:
        ...
    def eval(self, arg0: float) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def expand(self, arg0: int) -> None:
        ...
    def get_proj(self) -> numpy.ndarray[numpy.float64[m, n]]:
        ...
    def get_span(self) -> numpy.ndarray[numpy.float64[m, n]]:
        ...
class KrylovBackwardFilter:
    def __init__(self, master_equation: MEInference, obs_model: ObservationModel, obs_times: numpy.ndarray[numpy.float64[m, 1]], observations: numpy.ndarray[numpy.float64[m, 1]], initial: numpy.ndarray[numpy.float64[m, 1]], rates: numpy.ndarray[numpy.float64[m, 1]], obs_param: numpy.ndarray[numpy.float64[m, 1]], tspan: numpy.ndarray[numpy.float64[m, 1]]) -> None:
        ...
    def backward_filter(self) -> None:
        ...
    @typing.overload
    def eval_backward_filter(self, time: numpy.ndarray[numpy.float64[m, 1]]) -> numpy.ndarray[numpy.float64[m, n]]:
        ...
    @typing.overload
    def eval_backward_filter(self, time: float) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    @typing.overload
    def eval_forward_filter(self, time: numpy.ndarray[numpy.float64[m, 1]]) -> numpy.ndarray[numpy.float64[m, n]]:
        ...
    @typing.overload
    def eval_forward_filter(self, time: float) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    @typing.overload
    def eval_smoothed(self, time: numpy.ndarray[numpy.float64[m, 1]]) -> numpy.ndarray[numpy.float64[m, n]]:
        ...
    @typing.overload
    def eval_smoothed(self, time: float) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def forward_filter(self) -> None:
        ...
    def get_initial_smoothed(self) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def log_prob(self) -> float:
        ...
class KrylovFilter:
    def __init__(self, transition_model: MEInference, obs_model: ObservationModel, obs_times: numpy.ndarray[numpy.float64[m, 1]], observations: numpy.ndarray[numpy.float64[m, 1]], initial_dist: numpy.ndarray[numpy.float64[m, 1]], rates: numpy.ndarray[numpy.float64[m, 1]], obs_param: numpy.ndarray[numpy.float64[m, 1]]) -> None:
        ...
    def compute_rates_grad(self) -> None:
        ...
    def get_initial_grad(self) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def get_obs_param_grad(self) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def get_rates_grad(self) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def log_prob(self) -> float:
        ...
    def log_prob_backward(self) -> None:
        ...
class KrylovFilterMem(KrylovFilter):
    def __init__(self, transition_model: MEInference, obs_model: ObservationModel, obs_times: numpy.ndarray[numpy.float64[m, 1]], observations: numpy.ndarray[numpy.float64[m, 1]], initial_dist: numpy.ndarray[numpy.float64[m, 1]], rates: numpy.ndarray[numpy.float64[m, 1]], obs_param: numpy.ndarray[numpy.float64[m, 1]]) -> None:
        ...
class KrylovPropagator:
    def __init__(self, transition_model: MEInference, initial: numpy.ndarray[numpy.float64[m, 1]], rates: numpy.ndarray[numpy.float64[m, 1]], time: float) -> None:
        ...
    def backward(self, grad_output: numpy.ndarray[numpy.float64]) -> None:
        ...
    def compute_rates_grad(self) -> None:
        ...
    def eval(self, time: float) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def get_initial_grad(self) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def get_rates_grad(self) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def get_time_grad(self) -> float:
        ...
    def propagate(self) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
class KrylovSolver:
    @typing.overload
    def __init__(self, transition_model: MEInference, initial: numpy.ndarray[numpy.float64[m, 1]], rates: numpy.ndarray[numpy.float64[m, 1]], obs_times: numpy.ndarray[numpy.float64[m, 1]]) -> None:
        ...
    @typing.overload
    def __init__(self, transition_model: MEInference, initial: numpy.ndarray[numpy.float64[m, 1]], rates: numpy.ndarray[numpy.float64[m, 1]], obs_times: float) -> None:
        ...
    def backward(self, krylov_order: int, grad_output: numpy.ndarray[numpy.float64]) -> None:
        ...
    def compute_rates_grad(self) -> None:
        ...
    def forward(self, krylov_order: int = 1) -> numpy.ndarray[numpy.float64]:
        ...
    def get_initial_grad(self) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def get_rates_grad(self) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
class LogNormalNoise(NormalNoise):
    def __init__(self, exp_mu: numpy.ndarray[numpy.float64[m, 1]], sigma: numpy.ndarray[numpy.float64[m, 1]]) -> None:
        ...
class MEInference(MasterEquation):
    def __init__(self, model: MJP) -> None:
        ...
    def augmented_forward(self, time: float, backward: numpy.ndarray[numpy.float64], forward: numpy.ndarray[numpy.float64], rates: numpy.ndarray[numpy.float64]) -> numpy.ndarray[numpy.float64]:
        ...
    @typing.overload
    def forward(self, time: float, prob: numpy.ndarray[numpy.float64]) -> numpy.ndarray[numpy.float64]:
        ...
    @typing.overload
    def forward(self, time: float, prob: numpy.ndarray[numpy.float64], rates: numpy.ndarray[numpy.float64]) -> numpy.ndarray[numpy.float64]:
        ...
    def update_generator(self, rates: numpy.ndarray[numpy.float64[m, 1]]) -> None:
        ...
    @property
    def param_generators(self) -> list[scipy.sparse.csr_matrix]:
        ...
    @property
    def propensity_generators(self) -> list[scipy.sparse.csr_matrix]:
        ...
class MJP:
    name: str
    def __init__(self, name: str) -> None:
        ...
    @typing.overload
    def add_event(self, event: Event) -> None:
        ...
    @typing.overload
    def add_event(self, name: str, input_species: list[str], output_species: list[str], rate: float, hazard_callable: tuple, change_vec: list[int]) -> None:
        ...
    @typing.overload
    def add_rate(self, rate: Rate) -> None:
        ...
    @typing.overload
    def add_rate(self, name: str, value: float) -> None:
        ...
    @typing.overload
    def add_species(self, species: Species) -> None:
        ...
    @typing.overload
    def add_species(self, name: str, lower: int = 0, upper: int = 1, default_value: int = 0) -> None:
        ...
    def build(self) -> None:
        ...
    def build_state_map(self) -> numpy.ndarray[numpy.float64[m, n]]:
        ...
    @typing.overload
    def event_index(self, event: str) -> int:
        ...
    @typing.overload
    def event_index(self, event_list: list[str]) -> list[int]:
        ...
    def hazard(self, state: numpy.ndarray[numpy.float64]) -> numpy.ndarray[numpy.float64]:
        ...
    def ind2state(self, ind: int) -> numpy.ndarray[numpy.float64]:
        ...
    def parse_clusters(self, arg0: list[list[str]]) -> list[list[int]]:
        ...
    def propensity(self, state: numpy.ndarray[numpy.float64]) -> numpy.ndarray[numpy.float64]:
        ...
    def rate_index(self, rate: str) -> int:
        ...
    @typing.overload
    def species_index(self, species: str) -> int:
        ...
    @typing.overload
    def species_index(self, species_list: list[str]) -> list[int]:
        ...
    def state2ind(self, state: numpy.ndarray[numpy.float64]) -> int:
        ...
    def update_state(self, state: numpy.ndarray[numpy.float64], event: int) -> numpy.ndarray[numpy.float64]:
        ...
    @property
    def change_vectors(self) -> list[list[int]]:
        ...
    @property
    def default_state(self) -> list[float]:
        ...
    @property
    def dims(self) -> list[int]:
        ...
    @property
    def event_dict(self) -> dict:
        ...
    @property
    def event_list(self) -> list[str]:
        ...
    @property
    def input_species(self) -> list[list[int]]:
        ...
    @property
    def num_events(self) -> int:
        ...
    @property
    def num_rates(self) -> int:
        ...
    @property
    def num_species(self) -> int:
        ...
    @property
    def num_states(self) -> int:
        ...
    @property
    def output_species(self) -> list[list[int]]:
        ...
    @property
    def rate_array(self) -> numpy.ndarray[numpy.float64]:
        ...
    @property
    def rate_dict(self) -> dict:
        ...
    @property
    def rate_list(self) -> list[str]:
        ...
    @property
    def species_dict(self) -> dict:
        ...
    @property
    def species_list(self) -> list[str]:
        ...
class MasterEquation:
    def __init__(self, model: MJP) -> None:
        ...
    def forward(self, time: float, prob: numpy.ndarray[numpy.float64]) -> numpy.ndarray[numpy.float64]:
        ...
    @property
    def generator(self) -> scipy.sparse.csr_matrix:
        ...
    @property
    def hazard_generators(self) -> list[scipy.sparse.csr_matrix]:
        ...
    @property
    def model(self) -> MJP:
        ...
class NoiseModel:
    def __init__(self, param_list: list[Param]) -> None:
        ...
    def log_prob(self, obs: numpy.ndarray[numpy.float64[m, 1]]) -> float:
        ...
    def log_prob_grad(self, obs: numpy.ndarray[numpy.float64[m, 1]]) -> list[numpy.ndarray[numpy.float64[m, 1]]]:
        ...
    def sample(self, seed: int = 44404224) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    @property
    def param_list(self) -> list[str]:
        ...
class NormalNoise(NoiseModel):
    def __init__(self, mu: numpy.ndarray[numpy.float64[m, 1]], sigma: numpy.ndarray[numpy.float64[m, 1]]) -> None:
        ...
class ObservationModel:
    def __init__(self, transition_model: MJP, noise_type: str) -> None:
        ...
    @typing.overload
    def add_param(self, param: Param) -> None:
        ...
    @typing.overload
    def add_param(self, name: str, value: float) -> None:
        ...
    def add_transform(self, transform: Transform) -> None:
        ...
    def build(self) -> None:
        ...
    def log_prob(self, time: float, state: numpy.ndarray[numpy.float64[m, 1]], param: numpy.ndarray[numpy.float64[m, 1]], obs: numpy.ndarray[numpy.float64[m, 1]]) -> float:
        ...
    def log_prob_grad(self, time: float, state: numpy.ndarray[numpy.float64[m, 1]], param: numpy.ndarray[numpy.float64[m, 1]], obs: numpy.ndarray[numpy.float64[m, 1]]) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def log_prob_grad_vec(self, time: float, param: numpy.ndarray[numpy.float64[m, 1]], obs: numpy.ndarray[numpy.float64[m, 1]]) -> numpy.ndarray[numpy.float64[m, n]]:
        ...
    def log_prob_vec(self, time: float, param: numpy.ndarray[numpy.float64[m, 1]], obs: numpy.ndarray[numpy.float64[m, 1]]) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def sample(self, time: float, state: numpy.ndarray[numpy.float64[m, 1]], param: numpy.ndarray[numpy.float64[m, 1]], seed: int) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def transform(self, time: float, state: numpy.ndarray[numpy.float64[m, 1]], param: numpy.ndarray[numpy.float64[m, 1]], name: str) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def transform_vec(self, time: float, param: numpy.ndarray[numpy.float64[m, 1]], name: str) -> numpy.ndarray[numpy.float64[m, n]]:
        ...
    @property
    def noise_param_list(self) -> list[str]:
        ...
    @property
    def noise_type(self) -> str:
        ...
    @property
    def num_param(self) -> int:
        ...
    @property
    def obs_dim(self) -> int:
        ...
    @property
    def param_array(self) -> numpy.ndarray[numpy.float64]:
        ...
    @property
    def param_list(self) -> list[str]:
        ...
    @property
    def param_map(self) -> list[Param]:
        ...
    @property
    def param_parser(self) -> str:
        ...
class Param:
    name: str
    def __init__(self, name: str, value: numpy.ndarray[numpy.float64[m, 1]]) -> None:
        ...
    @property
    def value(self) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
class PosteriorSimulator:
    def __init__(self, transition_model: MJP, initial: numpy.ndarray[numpy.float64[m, 1]], tspan: numpy.ndarray[numpy.float64[m, 1]], seed: int, max_events: int = 100000, max_event_handler: str = 'warning') -> None:
        ...
    def simulate(self, t_grid: numpy.ndarray[numpy.float64], backward: numpy.ndarray[numpy.float64]) -> dict:
        ...
class Rate:
    def __init__(self, name: str, value: float = 1) -> None:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> float:
        ...
class Simulator:
    def __init__(self, model: MJP, initial_state: numpy.ndarray[numpy.float64[m, 1]], tspan: numpy.ndarray[numpy.float64[m, 1]], seed: int, max_events: int = 100000, max_event_handler: str = 'warning') -> None:
        ...
    @typing.overload
    def simulate(self) -> dict:
        ...
    @typing.overload
    def simulate(self, t_eval: numpy.ndarray[numpy.float64]) -> numpy.ndarray[numpy.float64]:
        ...
class Species:
    default: int
    index: int
    lower: int
    name: str
    upper: int
    def __init__(self, name: str, lower: int = 0, upper: int = 1, default: int = 0) -> None:
        ...
    @property
    def dim(self) -> int:
        ...
class Transform:
    def __init__(self, name: str, transform_callable: tuple, output_dim: int = 1, grad_callable: tuple = ()) -> None:
        ...
    def grad_param(self, time: float, state: numpy.ndarray[numpy.float64[m, 1]], param: numpy.ndarray[numpy.float64[m, 1]], grad_output: numpy.ndarray[numpy.float64[m, 1]]) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    def transform(self, time: float, state: numpy.ndarray[numpy.float64[m, 1]], param: numpy.ndarray[numpy.float64[m, 1]]) -> numpy.ndarray[numpy.float64[m, 1]]:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def output_dim(self) -> int:
        ...
def batched_filter(initial_dist: numpy.ndarray[numpy.float64], rates: numpy.ndarray[numpy.float64], transition_model: MEInference, observation_model: ObservationModel, obs_times: numpy.ndarray[numpy.float64], observations: numpy.ndarray[numpy.float64], obs_param: numpy.ndarray[numpy.float64], get_gradient: bool = False, num_workers: int = -1, backend: str = 'krylov') -> tuple:
    ...
def batched_filter_list(initial_dist: numpy.ndarray[numpy.float64], rates: numpy.ndarray[numpy.float64], transition_model: MEInference, observation_model: ObservationModel, obs_times: list, observations: list, obs_param: numpy.ndarray[numpy.float64], get_gradient: bool = False, num_workers: int = -1, backend: str = 'krylov') -> tuple:
    ...
@typing.overload
def simulate(transition_model: MJP, obs_model: ObservationModel, initial_state: numpy.ndarray[numpy.float64], rates: numpy.ndarray[numpy.float64], obs_param: numpy.ndarray[numpy.float64], t_eval: numpy.ndarray[numpy.float64], seed: int, max_events: int = 100000, max_event_handler: str = 'warning') -> numpy.ndarray[numpy.float64]:
    ...
@typing.overload
def simulate(transition_model: MJP, obs_model: ObservationModel, initial_state: numpy.ndarray[numpy.float64], t_eval: numpy.ndarray[numpy.float64], seed: int, max_events: int = 100000, max_event_handler: str = 'warning') -> numpy.ndarray[numpy.float64]:
    ...
@typing.overload
def simulate(transition_model: MJP, initial_state: numpy.ndarray[numpy.float64], rates: numpy.ndarray[numpy.float64], t_eval: numpy.ndarray[numpy.float64], seed: int, max_events: int = 100000, max_event_handler: str = 'warning') -> numpy.ndarray[numpy.float64]:
    ...
@typing.overload
def simulate(transition_model: MJP, initial_state: numpy.ndarray[numpy.float64], t_eval: numpy.ndarray[numpy.float64], seed: int, max_events: int = 100000, max_event_handler: str = 'warning') -> numpy.ndarray[numpy.float64]:
    ...
def simulate_batched(transition_model: MJP, obs_model: ObservationModel, initial_dist: numpy.ndarray[numpy.float64], rates: numpy.ndarray[numpy.float64], obs_param: numpy.ndarray[numpy.float64], t_obs: numpy.ndarray[numpy.float64], seed: int, num_samples: int = -1, num_workers: int = -1, max_events: int = 100000, max_event_handler: str = 'warning') -> numpy.ndarray[numpy.float64]:
    ...
@typing.overload
def simulate_full(transition_model: MJP, initial_state: numpy.ndarray[numpy.float64], rates: numpy.ndarray[numpy.float64], tspan: numpy.ndarray[numpy.float64], seed: int, max_events: int = 100000, max_event_handler: str = 'warning') -> dict:
    ...
@typing.overload
def simulate_full(transition_model: MJP, initial_state: numpy.ndarray[numpy.float64], tspan: numpy.ndarray[numpy.float64], seed: int, max_events: int = 100000, max_event_handler: str = 'warning') -> dict:
    ...
def simulate_posterior(master_equation: MEInference, obs_model: ObservationModel, initial_dist: numpy.ndarray[numpy.float64], rates: numpy.ndarray[numpy.float64], obs_param: numpy.ndarray[numpy.float64], tspan: numpy.ndarray[numpy.float64], t_obs: numpy.ndarray[numpy.float64], observations: numpy.ndarray[numpy.float64], t_grid: numpy.ndarray[numpy.float64], seed: int, max_events: int = 100000, max_event_handler: str = 'warning') -> dict:
    ...
def simulate_posterior_batched(master_equation: MEInference, obs_model: ObservationModel, initial_dist: numpy.ndarray[numpy.float64], rates: numpy.ndarray[numpy.float64], obs_param: numpy.ndarray[numpy.float64], tspan: numpy.ndarray[numpy.float64], t_obs: numpy.ndarray[numpy.float64], observations: numpy.ndarray[numpy.float64], t_grid: numpy.ndarray[numpy.float64], seed: int, num_samples: int = -1, num_workers: int = -1, max_events: int = 100000, max_event_handler: str = 'warning') -> list:
    ...
